### ISSUE TITLE
incompatibility with soul bound enchants.

### ISSUE THREAD

**Issue by DeRp-MaSte5** [franiscoder/dark-enchanting#17]
you crash when you use the dark enchanting table while having dark enchants installed. NOTE **i used a server, i have no idea on single player** 
[crash-2021-10-09_14.03.24-client.txt](https://github.com/frqnny/dark-enchanting/files/7316178/crash-2021-10-09_14.03.24-client.txt)

**Comment by Kronon-Conspirator** [comment]
Keyboard go brr
its Spellbound by TigerOfTroy , not soul bound by UpcraftLP.

the crash is caused by Spellbound's method of disabling enchantments by turning their max lvl into 0 which bugs out Dark Enchanter GUI when loading enchantment sliders. Spellbound 1.6.0 has Mounted turned off by default, turning it on in the spellbound config should fix it.
