### ISSUE TITLE
Crash on startup with version 1.0.0

### ISSUE THREAD

**Issue by HaXrDEV** [franiscoder/dark-enchanting#56]
Crash on startup with version 1.0.0 installed. Works fine with 0.7.0.
Crashlog: https://bytebin.lucko.me/74wpWwdh3N
Crashy: https://crashy.net/3NHrNCVUZalH7DGDXpQz

**Comment by frqnny** [comment]
Update all your mods.

Do you happen to have an outdated LibGUI jar in your mods folder? If so, update it to 5.4.0 as it is currently at 5.1.0. Perhaps there is a LibGUI jar that its overriding the jar inside Dark Enchanting.

Or perhaps another mod carries LibGUI inside their own jar and is loading and older version.

Either way, it can be fixed by updating all your mods hopefully

**Comment by Laifsyn** [comment]
Submit your latest.log file. There should pinpoint what's the mod that's loading the outdate libgui @HaXrBOT

**Comment by HaXrDEV** [comment]
I found out that it was actually 'Ok Zoomer' that was loading an old version of LibGUI. I would never have thought of this as a possible cause on my own. Thanks a ton!
